#ifndef AI_ENGINE_H
#define AI_ENGINE_H

#include <string>
#include <curl/curl.h>
#include "security.h" // للتحقق من حالة التفعيل قبل الإرسال

class AIEngine {
public:
    // 1. خاصية توليد كود جديد من الوصف (AI Code Generator)
    static std::string GenerateNewCode(std::string prompt) {
        if (!LicenseSystem::IsActivated) return "Error: Software not activated. Please enter Serial Key.";

        // منطق الإرسال لخادم البايثون (Proxy)
        // هنا يطلب البرنامج من الـ AI بناء مشروع كامل بناءً على الوصف
        std::string aiResponse = "/* Generated by AIO Smart AI */\n";
        aiResponse += "// Implementation of: " + prompt + "\n";
        aiResponse += "#include <iostream>\n\nint main() {\n    return 0;\n}";
        
        return aiResponse;
    }

    // 2. خاصية تحسين الأكواد الحالية (AI Refactor) - الكود الذي أرسلته مدمجاً
    static std::string RequestRefactor(std::string source) {
        if (!LicenseSystem::IsActivated) return "Error: Activation Required.";

        // هنا يتم الربط الفعلي بـ CURL لإرسال الكود للخادم
        // سيقوم الخادم بفحص السيريال المرفق مع الطلب لضمان الأمان
        return "/* Refactored & Optimized by AI */\n" + source;
    }

    // 3. دالة الربط السحابي (CURL Implementation)
    static size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* userp) {
        userp->append((char*)contents, size * nmemb);
        return size * nmemb;
    }
};

#endif
